name:                geoTime
version:             0.1.0.0
github:              "githubuser/geoTime"
license:             BSD3
author:              "Sumit Bakhli"
maintainer:          "sumit2bk@gmail.com"
copyright:           "2022 Sumit Bakhli"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sumit2bk/geoTime#readme>

executables:
  geoTime:
    main:                Main.hs
    source-dirs:         [src, src/service]
    other-modules:
    - Types
    - Args
    - App
    - GeoCoords
    - TimeZone
    dependencies:
    - base
    - text
    - aeson
    - mtl
    - req
    - optparse-applicative
    - bytestring
    - exceptions